### ISSUE TITLE
Bee docs missing some coverage for JSON schema

### ISSUE THREAD

**Issue by brettviren** [BNLIF/wire-cell-docs#1]
https://bnlif.github.io/wire-cell-docs/viz/uploads/

Two portions of the Bee JSON schema I do not find:

1. The `cluster_id` attribute of the "normal" Bee object
2. The entire "channel dead area" object.

When updating the docs, defining official names for each of these two types of objects would help future communications ("3D" vs "2D"? "live" vs "dead"? "points" vs "patches"?)

**Comment by czczc** [comment]
Added more information to the documents. Also added an "Additional files" section to describe the special files supported in Bee.
